### ISSUE TITLE
icmp request not there at eth1 interface when tcpdump

### ISSUE THREAD

**Issue by BurlyLuo** [DanPartelly/clab-minimal-vpp#1]
```
[root@rowan> 25-vpp-clab]# cat 1-setup-env.sh 
#!/bin/bash
set -v
cat <<EOF>clab.yaml | clab deploy -d -t clab.yaml -
name: cnf
topology:
  nodes:
    vpp1:
      kind: linux
      image: ligato/vpp-base
      binds:
        - config/vpp1:/etc/vpp
      exec:
        - bash -c 'apt update ; apt -y install tcpdump lrzsz net-tools'
      env:
        TZ: Asia/Shanghai
          
    vpp2:
      kind: linux
      image: ligato/vpp-base
      binds:
        - config/vpp2:/etc/vpp
      exec:
        - bash -c 'apt update ; apt -y install tcpdump lrzsz net-tools'
      env:
        TZ: Asia/Shanghai

  links:
    - endpoints: ["vpp1:eth1", "vpp2:eth1"]
EOF
[root@rowan> 25-vpp-clab]# 
```
when ping from vpp1 to vpp2. 
and capture the pcap at eth1 interface, but only see icmp replay no icmp request. why?
how the request transfer to vpp2?
